### ISSUE TITLE
python 2.6.x TypeError

### ISSUE THREAD

**Issue by gokhanm** [gokhanm/psystem#1]
``` python
>>> get.ntp_current_time
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/psystem-0.1-py2.6.egg/psystem/system.py", line 73, in ntp_current_time
    msg = bytes('\x1b' + 47 * '\0', 'UTF-8')
TypeError: str() takes at most 1 argument (2 given)
```

**Comment by gokhanm** [comment]
Fixed with [4ca8ee8](https://github.com/gokhanm/psystem/commit/4ca8ee8322cd26383fee8a7dbd9863e58e63f484) commit
